### PR TITLE
To simplify config methods use derived classes like

### PR DESCRIPTION
**Pull request by FrankPfattheicher**
```
public class ExecuteCodeConfigFile : UnitTests.TestContainer.TestConfig
{
    public void Load()
    {
        IntMember = 42;
    }
}
```

so there is no need to use "config." on each line.

Be more strict in method naming using "Load()" only.
This allows local methods within the class.

### CODE REVIEW

**Comment by wolfspelz** [comment]
Copying all property values back and forth is a bit wild. But using a derived class is a cool idea. Also, allowing local methods by restricting the invoked member name is better. Lets go for it.

**Comment by FrankPfattheicher** [comment]
"Copying all property values back and forth is a bit wild."
Yes it is - i investigated long - very long - to do it an other way.
But i found no way - and i thing there is no way to 
1. Instantiate a derived INSTANCE of an existing object
2. Cast an existing instance to a derived type (not even with brute force)

But i keep this issue in mind...

**Comment by wolfspelz** [comment]
But an innovative idea. Now the API is as it should be. Maybe we can improve internals later. Maybe it's good enough. 

I made the new style the default. Broke some unit tests. Include() gave me a hard time. Learning: don't accept changes with the backward compatible code still active :-)

Will push soon.

**Comment by wolfspelz** [comment]
The old approach with any class name and any method name was so arbitrary. I always had the feel, that it's too arbitrary. Now it's well defined. Not to forget setting properties direct without a config.

**Pull request merged**
